### ISSUE TITLE
Move Integrity bytes to Passwd_file

### ISSUE THREAD

**Issue by rwedoff** [rwedoff/Password-Manager#12]
Integrity bytes are currently in master_passwd and needs to be moved to passwd_file.  Shouldn't be too terrible.

**Comment by rwedoff** [comment]
Done, not really sure what I did, well, I am not confident in what I did but it works...check it out maybe?
@theliamcrawford

**Comment by theliamcrawford** [comment]
From what I can tell, everything works properly. You left a print line uncommented in our integrity check, but that was a quick fix

**Comment by theliamcrawford** [comment]
Only thing is, it ouputs a 0 after a successful master password input.

**Comment by rwedoff** [comment]
Outputs a 0?

**Comment by theliamcrawford** [comment]
Prints it to the terminal, I mean.
